source "http://rubygems.org"
source "http://gems.github.com"
source "http://gemcutter.org"

gem "rails", "2.3.11"
gem "sqlite3"
gem "i18n", "0.4.1"
gem "mongrel"
gem "calendar_date_select"
gem "builder"
gem "spreadsheet", "~> 0.6.5.6"
